spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_bookmanager?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    date-format: yyyy-MM-dd

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


mybatis:
  type-aliases-package: com.xyq.pojo
  mapper-locations:
    - classpath:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl







